FROM	ruby:4.0.1-alpine3.23
LABEL maintainer "Jessie Frazelle <jess@linux.com>"

RUN apk add --no-cache \
	coreutils

RUN	set -x \
	&& apk add --no-cache --virtual .build-deps \
	build-base \
	&& gem install gmail-britta --no-document \
	&& apk del .build-deps
